### ISSUE TITLE
Linux Version?

### ISSUE THREAD

**Issue by KitChaos-DreamscapeStudios** [ParadoxGameConverters/EU4ToVic3#512]
Hey, I see some files within the source that seem linux targeted, but I can't seem to find a linux build or executable of the converter. Are there instructions on how to use the converter on linux, if possible? If it cannot be done, I would love if that could be specified

**Comment by Zemurin** [comment]
We do linux builds regularly, but only for testing purposes. Workflow can be found here:
https://github.com/ParadoxGameConverters/EU4ToVic3/blob/master/.github/workflows/linux_codeql-analysis.yml
Look for "Analyze Foreign" section. If you have a working knowledge of how to compile code on Linux, you should be able to follow these, more or less.

Otherwise, we don't support linux and there are no guides. We don't have anyone on team using either Linux or Mac.
