### ISSUE TITLE
Various laws conversion

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/EU4toVic3#85]
# Army
Based on EU4 professionalism. If less than 60%, use `law_peasant_levies`; else, use `law_professional_army`

# Bureaucracy
- `law_elected_bureaucrats`: Universal Suffrage, Parliamentarism
- `law_appointed_bureaucrats`: Centralized Bureaucracy, Sidhi Recruitment, Appointment by Committee, Subservient Bureaucrats, Zealous Administrators
- `law_hereditary_bureaucrats` is the fallback

# Child labor
At start, `law_child_labor_allowed` should be given to all countries

# Church and State
`law_state_religion` should be given to all countries

# Cultural acceptance
- `law_multicultural` should be given to Empire Ranks with more than 8 accepted cultures
- `law_racial_segregation` and `law_national_supremacy` should be considered the default (difference is whether slavery is still allowed or not)

# Colonialism
Based on native policies:
- `law_colonial_exploitation` if Native Repression Policy
- `law_colonial_resettlement`if Native Trading Policy or Native Coexistence Policy
- `law_no_colonial_affairs` if there is no policy (and thus no colonialism)

# Separation of powers
- `law_oligarchy`: Oligarchy (Republic), Plutocracy (Republic), Noble Elite (Republic), Revolutionary Republic, Free City, Trading City, Veche Republic, American Republic, Colonial Government, Dutch Republic, Kongsi Federation, Aristocratic Court, Legislative Sejm
- `law_elder_council`: Tribal government
- `law_landed_voting`: Autonomous Swiss Cantons, Landholders, Military Electorate, Parliamentarism, General Estates, States General, The Feuillant System
- `law_wealth_voting`: Federal Republic, Citizenry
- `law_census_voting`: Three Social Classes, The Two-Chamber System
- `law_anarchy`: Pirate Republic, Peasants Republic, Self-Governing Colony, Sich Rada
- `law_universal_suffrage`: Equal Electorate
- `law_autocracy`: fallback

# Economic system
Until sound mappings are found, fallback on `law_traditionalism`

# Schooling
`law_religious_schools` to be given to all Protestant countries and to all countries who are tech tier 1 or 2.
Any other country will have `law_no_schools`

# Free speech
Default to `law_censorship`. Use `law_outlawed_dissent` for countries at negative stability.

# Governments
- `law_chiefdom`: Tribal government
- `law_monarchy`: Monarchy government
- `law_parliamentary_republic`: Republic government with any of the following: Protectorate Parliament, Venetian Government, Noble Elite, Free City, Veche Republic, Colonial Government, Dutch Republic, Kongsi Federation, Autonomous Swiss Cantons
- `law_presidential_republic`: Any other Republic government
- `law_theocracy`: Theocracy government

# Health system
`law_no_health_system` for all countries

# Internal security
`law_no_home_affairs` for all countries

# Slavery and serfdom
`law_serfdom` for countries that still have slavery accepted in EU4, `law_serfdom_banned` and `law_slavery_banned` for all remaining ones
Countries accepting slavery will also have:
- `law_debt_slavery` if they lack colonists
- `law_slave_trade` if they have colonists

# Migration
`law_no_migration_controls` for all countries

# Police
`law_local_police` for all countries with `law_professional_army`; `law_no_police` otherwise

# Women rights
`law_no_womens_rights` for all countries

# Taxation
`law_land_based_taxation` for all countries

# Trade
- `law_mercantilism` to all countries with more than 20% mercantilism
- `law_free_trade` to Pirate Republics and Tribal governments, as well as all decentralized tags
- `law_protectionism` to all remaining Western and Eastern countries
- `law_isolationism` to all remaining centralized tags

# Welfare
`law_no_social_security` for all countries

**Comment by gawquon** [comment]
Update from the perspective of valid laws at the beginning of the game. All laws listed here are used by at least one country at the start of the game unless denoted. Completely omitted are laws that reqiure techs beyond what the most advanced country starts out with.

# Power Sctructure
## Governance Principles
- `law_chiefdom`* Decentralized Only
- `law_monarchy`
- `law_presidential_republic`
- `law_parliamentary_republic`
- `law_theocracy`* Mutually exclusive with Total Separation

Note: All Decentralzied nations should get a preset of laws instead of the mapping process.
## Distribution of Power
- `law_autocracy`* Mutually exclusive with Elected Bureaucrats
- `law_oligarchy`* Mutually exclusive with Elected Bureaucrats
- `law_landed_voting`
- `law_wealth_voting`
- `law_census_voting`
- `law_universal_suffrage`* No Vanilla country starts with this
## Citizenship
- `law_national_supremacy`
- `law_racial_segregation`
- `law_cultural_exclusion`* Mutually exclusive with Slave Trade & Legacy 
- `law_multicultural`* Mutually exclusive with all Slavery
## Church and State
- `law_state_religion`
- `law_freedom_of_conscience`
- `law_total_separation`* Mutually exclusive with Theocracy
## Bureaucracy
- `law_hereditary_bureaucrats`
- `law_appointed_bureaucrats`
- `law_elected_bureaucrats`* No Vanilla country starts with this, mutually exclusive with Oligarchy & Autocracy
## Army Model
- `law_peasant_levies`
- `law_professional_army`
- `law_national_militia`
## Internal Security
- `law_no_home_affairs`
- `law_national_guard`
- `law_secret_police`* No Vanilla country starts with this
- `law_guaranteed_liberties`* No Vanilla country starts with this
# Economy
## Economic System
- `law_traditionalism`* Mutually exclusive with Per Capita and Proportional Tax
- `law_interventionism`* Mutually exclusive with Serfdom
- `law_agrarianism`
- `law_laissez_faire`* Mutually exclusive with Isolationism & Serfdom
## Trade Policy
- `law_mercantilism`
- `law_protectionism`
- `law_free_trade`
- `law_isolationism`* Mutually exclusive with Lazzez-Faire
## Taxation
- `law_consumption_based_taxation`
- `law_land_based_taxation`
- `law_per_capita_based_taxation`* Mutually exclusive with Traditionalism
- `law_proportional_taxation`* No Vanilla country starts with this, Mutually exclusive with Traditionalism
## Colonzation
- `law_no_colonial_affairs`
- `law_colonial_resettlement` 
- `law_colonial_exploitation`
## Policing
- `law_no_police`
- `law_local_police`
- `law_dedicated_police`
## Education System
- `law_no_schools`
- `law_religious_schools`
- `law_private_schools`
- `law_public_schools`
## Health System
- `law_no_health_system`
- `law_charitable_health_system`
# Human Rights
## Free Speech
- `law_censorship`
- `law_right_of_assembly`
## Labor Rights
- `law_serfdom_banned`
- `law_serfdom` * Mutually exclusive with Interventionism and Laissez-Faire
## Children's Rights
- `law_child_labor_allowed`
## Rights of Women
- `law_no_womens_rights`
- `law_women_own_property`
## Welfare
- `law_no_social_security`
- `law_poor_laws`
## Migration
- `law_no_migration_controls`
- `law_migration_controls`
- `law_closed_borders`
## Slavery
- `law_slavery_banned`
- `law_debt_slavery`* Mutually exclusive with Multiculturalism
- `law_slave_trade`* Mutually exclusive with Multiculturalism & Cultural Exclusion
- `law_legacy_slavery`* Mutually exclusive with Multiculturalism & Cultural Exclusion
